### ISSUE TITLE
Crash when closing a window and then opening a new one

### ISSUE THREAD

**Issue by nstoddard** [PistonDevelopers/glfw-rs#313]
I found some code that causes a crash:

```
extern crate glfw;

fn main() {
    let glfw = glfw::init(glfw::FAIL_ON_ERRORS).unwrap();

    let (mut window, events) = glfw.create_window(100, 100, "test", glfw::WindowMode::Windowed).unwrap();
    window.set_all_polling(true);
    drop((window,events));

    glfw.create_window(100, 100, "test", glfw::WindowMode::Windowed).unwrap();
}
```

This fails with:

```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', C:/bot/slave/nightly-dist-rustc-win-64/build/src/libcore\result.rs:768
thread '<main>' panicked at 'internal error: entered unreachable code', C:/bot/slave/nightly-dist-rustc-win-64/build/src/libstd\sync\mpsc/mod.rs:558
```

I'm using 64-bit windows, I haven't tested other platforms. This looks like it could be a bug in the rust libraries (due to the 'entered unreachable code' part), but I'm reporting it here because I don't know how to reproduce it without using glfw-rs.

Replacing the call to `drop` with `drop(window)` results in a different error:

```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', C:/bot/slave/nightly-dist-rustc-win-64/build/src/libcore\result.rs:768
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', C:/bot/slave/nightly-dist-rustc-win-64/build/src/libcore\option.rs:362
stack backtrace:
   1:           0x4a95c7 - main
   2:           0x4bd462 - main
   3:           0x4274c0 - main
   4:           0x4278c5 - main
   5:           0x4bccea - main
   6:           0x4d98b9 - main
   7:           0x4d2e65 - main
   8:           0x404053 - main
   9:           0x401ca2
  10:           0x4bf91c - main
  11:           0x4bf8f9 - main
  12:           0x4bdd0a - main
  13:           0x4013b5
  14:           0x4014e8
  15:         0x76a759ed - BaseThreadInitThunk
thread panicked while panicking. aborting.
An unknown error occurred
```

**Comment by bjz** [comment]
Hmm, might also be that we are violating some invariants in glfw-rs' unsafe blocks.

**Comment by coderedart** [comment]
In 2025, cannot reproduce this crash.
