### ISSUE TITLE
create_window_surface

### ISSUE THREAD

**Issue by uhuntu** [PistonDevelopers/glfw-rs#465]
I have a commit here to test create_window_surface

https://github.com/uhuntu/glfw-rs/commit/cb2a4bb1cd886796c465e66aa45d92f17f8f2b5f

However, when I run, it will show
```
C:\Users\hunt\source\repos\glfw-rs>cargo run --example vulkan
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target\debug\examples\vulkan.exe`
Vulkan required extensions: ["VK_KHR_surface", "VK_KHR_win32_surface"]
error: process didn't exit successfully: `target\debug\examples\vulkan.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```

**Comment by uhuntu** [comment]
Seems I had resolved it by https://github.com/uhuntu/glfw-rs/commit/d4cc9033b62c36b533c1d5516d6c0623676375eb

Then I meet the trouble below,
```
C:\Users\hunt\source\repos\glfw-rs>cargo run --example vulkan
    Finished dev [unoptimized + debuginfo] target(s) in 0.15s
     Running `target\debug\examples\vulkan.exe`
thread 'main' panicked at 'GLFW Error: Cannot make current with a window that has no OpenGL or OpenGL ES context', src\lib.rs:427:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\examples\vulkan.exe` (exit code: 101)
```

**Comment by uhuntu** [comment]
Finally I managed it, https://github.com/uhuntu/glfw-rs/commit/c5b2cae0a440aca598e1081b1acf6477fa138ec9

It's very close to finish.
```
C:\Users\hunt\source\repos\glfw-rs>cargo run --example vulkan
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target\debug\examples\vulkan.exe`
Vulkan required extensions: ["VK_KHR_surface", "VK_KHR_win32_surface"]
thread 'main' panicked at 'GLFW Error: Win32: Vulkan instance missing VK_KHR_win32_surface extension', src\lib.rs:427:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\examples\vulkan.exe` (exit code: 101)
```
